---

- name: EC2 | Register LB | Gather EC2 Info by Name
  amazon.aws.ec2_instance_info:
    filters:
      "tag:Name": "{{ machine.name }}"
  register: ec2_out

- name: EC2 | Register LB | Discovery Instance IP
  ansible.builtin.set_fact:
    machine_target_id: "{{ ec2_out.instances[0].private_ip_address }}"
  when: reg.resource_type == 'ip'

- name: EC2 | Register LB | Discovery Instance ID
  ansible.builtin.set_fact:
    machine_target_id: "{{ ec2_out.instances[0].instance_id }}"
  when: reg.resource_type == 'instanceId'

- name: EC2 | Register LB | "Attach EC2 to the Target Group {{ reg.resource_name }}"
  community.aws.elb_target:
    target_group_name: "{{ reg.resource_name }}"
    target_id: "{{ machine_target_id }}"
    state: present
