---
- name: AWS EC2 | debug show spec
  ansible.builtin.debug:
    var: machine
  when: debug|d(false)

- name: AWS EC2 | Ensuring IAM role exists
  community.aws.iam_role:
    name: "{{ machine.instance_role }}"
    state: present
    description: "Instance Profile for {{ machine.instance_role }}"
    assume_role_policy_document: "{{ machine.instance_role_spec.\
        assume_role_policy_document |\
        d(lookup('file','iam-role-policy-ec2.json')) \
      }}"
    managed_policies: "{{ machine.instance_role_spec.\
                          managed_policies |d(omit) }}"
    policy_document: "{{ machine.instance_role_spec.policy_document |d(omit) }}"
    tags: "{{ machine.instance_role_spec.tags |d(omit) }}"
  register: iam_create

- name: AWS EC2 | Ensuring IAM policy exists
  community.aws.iam_policy:
    iam_type: role
    iam_name: "{{ machine.instance_role }}"
    policy_name: "{{ machine.iam_policy_name }}"
    state: present
    policy_json: "{{ machine.instance_policy_spec.policy_json }}"
  when: machine.iam_policy_name is defined

- name: AWS EC2 | Discovery subnet ID
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      "tag:Name": "{{ machine.vpc_subnet_name }}"
  register: sb_out
  when: machine.vpc_subnet_name is defined

- name: AWS EC2 | Check subnet ID
  ansible.builtin.assert:
    that:
      - sb_out.subnets|length > 0
    fail_msg: "'subnet_ids' is empty.\
              Unable to find subnet with name '{{ machine.vpc_subnet_name }}'"

- name: AWS EC2 | Set subnet ID from name
  ansible.builtin.set_fact:
    subnet_id: "{{ sb_out.subnets[0].subnet_id }}"
  when: machine.vpc_subnet_name is defined

- name: AWS EC2 | Discovery subnet ID from name
  ansible.builtin.set_fact:
    subnet_id: "{{ machine.vpc_subnet_id }}"
  when: machine.vpc_subnet_id is defined

- name: AWS EC2 | Creating instance(s)
  amazon.aws.ec2_instance:
    user_data: "{{ machine.user_data | string }}"
    availability_zone: "{{ machine.availability_zone |d(omit) }}"
    cpu_credit_specification: "{{ machine.cpu_credit_specification |d(omit) }}"
    cpu_options: "{{ machine.cpu_options |d(omit) }}"
    detailed_monitoring: "{{ machine.detailed_monitoring |d(omit) }}"
    ebs_optimized: "{{ machine.ebs_optimized |d(omit) }}"
    ec2_url: "{{ machine.ec2_url |d(omit) }}"
    filters: "{{ machine.filters |d(omit) }}"
    image_id: "{{ machine.image_id |d(omit) }}"
    instance_role: "{{ machine.instance_role |d(omit) }}"
    instance_type: "{{ machine.instance_type }}"
    key_name: "{{ machine.key_name |d(omit) }}"
    launch_template: "{{ machine.launch_template |d(omit) }}"
    metadata_options: "{{ machine.metadata_options |d(omit) }}"
    network: "{{ machine.network |d(omit) }}"
    placement_group: "{{ machine.placement_group |d(omit) }}"
    purge_tags: "{{ machine.purge_tags |d(omit) }}"
    region: "{{ machine.region |d(omit) }}"
    security_group: "{{ machine.security_group |d(omit) }}"
    security_groups: "{{ machine.security_groups |d(omit) }}"
    state: "{{ machine.state | d(omit) }}"
    tags: "{{ machine.tags | d(omit) }}"
    tenancy: "{{ machine.tenancy | d(omit) }}"
    termination_protection: "{{ machine.termination_protection | d(omit) }}"
    tower_callback: "{{ machine.tower_callback | d(omit) }}"
    # There's a bug on the default var '(omit)' when using ign (json),
    # the module is not property formating the user_data from vars,
    # then the node will not run correctly on the boot.
    volumes: "{{ machine.volumes | d(omit) }}"
    vpc_subnet_id: "{{ subnet_id | d(omit) }}"
    wait: "{{ machine.wait | d(omit) }}"
    wait_timeout: "{{ machine.wait_timeout |d(omit) }}"
  register: machine_out

- name: AWS EC2 | Machine created spec
  ansible.builtin.debug:
    var: machine_out
  when: debug|d(false)

- name: AWS EC2 | Waiting a moment to propagate the request
  ansible.builtin.pause:
    seconds: 10
  when:
   - not(machine.wait)
   - machine_out.changed

- name: AWS EC2 | Register to resource Load Balancer
  ansible.builtin.include_tasks: "aws-register-{{ reg.service }}.yml"
  with_items: "{{ machine.register_resources | d([]) }}"
  loop_control:
    loop_var: reg
