---
- name: DO | debug show spec
  debug:
    var: machine

- set_fact:
    vpc_uuid: "{{ machine.vpc_uuid | d('') }}"
    image_id: "{{ machine.image_id | d('') }}"

# API does not return when member=true name=vpc_name
- name: Compute | DO | Lookup for vpc_uuid
  community.digitalocean.digital_ocean_vpc_info:
  register: do_vpc
  when: vpc_uuid == ''

- debug: var=do_vpc

- name: Compute| DO | Set vpc_uuid
  set_fact:
    vpc_uuid: "{{ do_vpc.data | json_query(filter_vpc) | join(' ') }}"
  when: 
    - vpc_uuid == ''
    - not(do_vpc.failed)
  vars:
    filter_vpc: "[?name=='{{ machine.vpc_name }}'].id"

- debug: var=vpc_uuid

- name: Gather information about all images
  community.digitalocean.digital_ocean_image_info:
    image_type: private
  when: image_id == ''
  register: do_img

- debug: var=do_img

- name: Compute| DO | Set image_id
  set_fact:
    image_id: "{{ do_img.data | json_query(filter_image) | join(' ') }}"
  when: 
    - image_id == ''
    - not(do_img.failed)
  vars:
    filter_image: "[?name=='{{ machine.image_name }}'].id"

- name: Create ssh key
  community.digitalocean.digital_ocean_sshkey:
    name: "{{ machine.ssh_key.name }}"
    ssh_pub_key: "{{ machine.ssh_key.pub_key }}"
    state: present
  register: do_sshk

- debug: var=do_sshk

- name: Create a new Droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    name: "{{ machine.name }}"
    unique_name: yes
    project_name: "{{ machine.project_name }}"
    size: "{{ machine.size }}"
    region: "{{ machine.region }}"
    image: "{{ image_id }}"
    user_data: "{{ machine.user_data }}"
    ssh_keys: "{{ [do_sshk.data.ssh_key.id] | d([omit]) }}"
    private_networking: "{{ machine.private_networking | d(omit) }}"
    vpc_uuid: "{{ machine.vpc_uuid | d(vpc_uuid) }}"
    wait_timeout: 500
  register: do_machine

- name: EC2 | debug Machine created
  debug:
    var: do_machine

#- name: Register EC2 to resources
#  include: "aws-register-{{ reg.service }}.yml"
#  with_items: "{{ machine.register_resources | d([]) }}"
#  loop_control:
#    loop_var: reg
