---

- name: OCI | Callback | Describe nlb
  oracle.oci.oci_network_load_balancer_facts:
    compartment_id: "{{ machine_spec.compartment_id }}"
    display_name: "{{ cb.nlb_name }}"
  register: _nlbs

- name: OCI | Callback | Set NLB ID
  ansible.builtin.set_fact:
    nlb_id: "{{ (_nlbs.network_load_balancers | first).id }}"

- name: OCI | Callback | Backend
  ansible.builtin.include_tasks: "./cb_nlb_backend.yaml"
  loop: "{{ cb.backend_sets }}"
  loop_control:
    loop_var: nlb_be
